{
 "title": "Projeto Final - Observabilidade",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Métricas: CPU Usage (Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Rastreio de Pedidos (Tempo)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "70e85b8a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "users-service",
        "products-service"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    },
    { "limit": 20, "tableType": "traces" }
   ]
  },
  {
   "title": "Monitorização de Logs em Tempo Real",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container_name=~\".+\"} | json | level!=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Eventos e Erros  Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{job=~\".+\"} | json | __error__=\"\"",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "Intensidade de operações (Logs/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=~\".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total de Pedidos (Ùltima Hora)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\".+\"} |= \"HTTP\" [1h]))"
    }
   ]
  }
 ]
}